################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../my_web_socket/hash/blake2b.c \
../my_web_socket/hash/blake2b160.c \
../my_web_socket/hash/blake2b256.c \
../my_web_socket/hash/blake2b384.c \
../my_web_socket/hash/blake2b512.c \
../my_web_socket/hash/blake2s.c \
../my_web_socket/hash/blake2s128.c \
../my_web_socket/hash/blake2s160.c \
../my_web_socket/hash/blake2s224.c \
../my_web_socket/hash/blake2s256.c \
../my_web_socket/hash/md2.c \
../my_web_socket/hash/md4.c \
../my_web_socket/hash/md5.c \
../my_web_socket/hash/ripemd128.c \
../my_web_socket/hash/ripemd160.c \
../my_web_socket/hash/sha1.c \
../my_web_socket/hash/sha224.c \
../my_web_socket/hash/sha256.c \
../my_web_socket/hash/sha384.c \
../my_web_socket/hash/sha3_224.c \
../my_web_socket/hash/sha3_256.c \
../my_web_socket/hash/sha3_384.c \
../my_web_socket/hash/sha3_512.c \
../my_web_socket/hash/sha512.c \
../my_web_socket/hash/sha512_224.c \
../my_web_socket/hash/sha512_256.c \
../my_web_socket/hash/tiger.c \
../my_web_socket/hash/whirlpool.c 

OBJS += \
./my_web_socket/hash/blake2b.o \
./my_web_socket/hash/blake2b160.o \
./my_web_socket/hash/blake2b256.o \
./my_web_socket/hash/blake2b384.o \
./my_web_socket/hash/blake2b512.o \
./my_web_socket/hash/blake2s.o \
./my_web_socket/hash/blake2s128.o \
./my_web_socket/hash/blake2s160.o \
./my_web_socket/hash/blake2s224.o \
./my_web_socket/hash/blake2s256.o \
./my_web_socket/hash/md2.o \
./my_web_socket/hash/md4.o \
./my_web_socket/hash/md5.o \
./my_web_socket/hash/ripemd128.o \
./my_web_socket/hash/ripemd160.o \
./my_web_socket/hash/sha1.o \
./my_web_socket/hash/sha224.o \
./my_web_socket/hash/sha256.o \
./my_web_socket/hash/sha384.o \
./my_web_socket/hash/sha3_224.o \
./my_web_socket/hash/sha3_256.o \
./my_web_socket/hash/sha3_384.o \
./my_web_socket/hash/sha3_512.o \
./my_web_socket/hash/sha512.o \
./my_web_socket/hash/sha512_224.o \
./my_web_socket/hash/sha512_256.o \
./my_web_socket/hash/tiger.o \
./my_web_socket/hash/whirlpool.o 

C_DEPS += \
./my_web_socket/hash/blake2b.d \
./my_web_socket/hash/blake2b160.d \
./my_web_socket/hash/blake2b256.d \
./my_web_socket/hash/blake2b384.d \
./my_web_socket/hash/blake2b512.d \
./my_web_socket/hash/blake2s.d \
./my_web_socket/hash/blake2s128.d \
./my_web_socket/hash/blake2s160.d \
./my_web_socket/hash/blake2s224.d \
./my_web_socket/hash/blake2s256.d \
./my_web_socket/hash/md2.d \
./my_web_socket/hash/md4.d \
./my_web_socket/hash/md5.d \
./my_web_socket/hash/ripemd128.d \
./my_web_socket/hash/ripemd160.d \
./my_web_socket/hash/sha1.d \
./my_web_socket/hash/sha224.d \
./my_web_socket/hash/sha256.d \
./my_web_socket/hash/sha384.d \
./my_web_socket/hash/sha3_224.d \
./my_web_socket/hash/sha3_256.d \
./my_web_socket/hash/sha3_384.d \
./my_web_socket/hash/sha3_512.d \
./my_web_socket/hash/sha512.d \
./my_web_socket/hash/sha512_224.d \
./my_web_socket/hash/sha512_256.d \
./my_web_socket/hash/tiger.d \
./my_web_socket/hash/whirlpool.d 


# Each subdirectory must supply rules for building sources it contributes
my_web_socket/hash/blake2b.o: ../my_web_socket/hash/blake2b.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2b.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2b160.o: ../my_web_socket/hash/blake2b160.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2b160.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2b256.o: ../my_web_socket/hash/blake2b256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2b256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2b384.o: ../my_web_socket/hash/blake2b384.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2b384.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2b512.o: ../my_web_socket/hash/blake2b512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2b512.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2s.o: ../my_web_socket/hash/blake2s.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2s.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2s128.o: ../my_web_socket/hash/blake2s128.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2s128.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2s160.o: ../my_web_socket/hash/blake2s160.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2s160.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2s224.o: ../my_web_socket/hash/blake2s224.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2s224.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/blake2s256.o: ../my_web_socket/hash/blake2s256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/blake2s256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/md2.o: ../my_web_socket/hash/md2.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/md2.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/md4.o: ../my_web_socket/hash/md4.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/md4.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/md5.o: ../my_web_socket/hash/md5.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/md5.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/ripemd128.o: ../my_web_socket/hash/ripemd128.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/ripemd128.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/ripemd160.o: ../my_web_socket/hash/ripemd160.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/ripemd160.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha1.o: ../my_web_socket/hash/sha1.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha1.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha224.o: ../my_web_socket/hash/sha224.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha224.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha256.o: ../my_web_socket/hash/sha256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha384.o: ../my_web_socket/hash/sha384.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha384.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha3_224.o: ../my_web_socket/hash/sha3_224.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha3_224.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha3_256.o: ../my_web_socket/hash/sha3_256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha3_256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha3_384.o: ../my_web_socket/hash/sha3_384.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha3_384.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha3_512.o: ../my_web_socket/hash/sha3_512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha3_512.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha512.o: ../my_web_socket/hash/sha512.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha512.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha512_224.o: ../my_web_socket/hash/sha512_224.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha512_224.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/sha512_256.o: ../my_web_socket/hash/sha512_256.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/sha512_256.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/tiger.o: ../my_web_socket/hash/tiger.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/tiger.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
my_web_socket/hash/whirlpool.o: ../my_web_socket/hash/whirlpool.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Inc -I../Drivers/CMSIS/Include -I../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../Drivers/STM32F7xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/common" -I"E:/Users/StefanoParacchino/STM32CubeIDE/workspace_1.0.1/NUCLEO-WebSocket/my_web_socket_Head/cyclone_ssl" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"my_web_socket/hash/whirlpool.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

